### ISSUE TITLE
Building environment

### ISSUE THREAD

**Issue by Ukhupacha** [BoPang1996/TubeTK#3]
Hello,
I've been trying to reproduce the code without much success.

Rank: 0 Start!
Building TubeTK Model
reading video...
100%|████████████████████████████████████████████████████████████████████████████▉| 2077/2080 [00:37<00:00, 57.74it/s]finish_reading
100%|█████████████████████████████████████████████████████████████████████████████| 2080/2080 [00:37<00:00, 54.89it/s]
==> Validation data : 2073
Loading Model
Finish Loading
  0%| | 0/691 [00:00Traceback (most recent call last):
  File "launch.py", line 95, in <module>
    main()
  File "launch.py", line 91, in main
    cmd=process.args)
subprocess.CalledProcessError: Command '**['/home/jugonzal/anaconda3/envs/tubetk/bin/python', '-u', 'demo.py', '--local_rank=0', '--batch_size=3', '--config', 'configs/TubeTK_resnet_50_FPN_8frame_1stride.yaml', '--video_url', './videos/', '--output_dir', './vis_video']' died with <Signals.SIGSEGV: 11>.**

I think that it is probably of the cross compilation on libraries.
Could you be so kind and share the builing envionment?
I'm using CUDA 9.2 and cudnn/7.1-cuda-9.2, I installed apex cause I do not have GPU>16GB and I correctly install the requirements.txt dependencies, I think I may be missing something

Thanks a lot,

Ukhu

**Comment by BoPang1996** [comment]
Seems like a problem caused by Apex. Could you please try to run "demo.py" without '--apex' to confirm whether it is caused by Apex?. Evaluation mode does not need so much GPU memory.

**Comment by cadrev** [comment]
Also having this issue as well even if I use no apex flags on running the demo. Currently using Cuda 10.1 with GTX1080.

**Comment by Ukhupacha** [comment]
Same here, could you share your conda env? I had to install a couple more dependencies that were not in the requirements.txt

**Comment by liyz15** [comment]
[environment.txt](https://github.com/BoPang1996/TubeTK/files/4969784/environment.txt)
Here is the conda environment we used, exported with
```conda env export > environment.yml```

Please also make sure your cudatoolkit (```conda list | grep cudatoolkit```) and CUDA version (```cat /usr/local/cuda/version.txt```) are the same.

**Comment by BoPang1996** [comment]
And please also upgrade your gcc version to > 5.0 (our version is 5.4.0 20160609).

**Comment by Mohammed-Abouzid** [comment]
@Ukhupacha 
have you discovered the solution for this situation? so please share it with me

**Comment by Ukhupacha** [comment]
On my side, I rebuild it with cuda 10.2 and a greater version of gcc. 

Also, I added to the file post_processing/nms/src/nms_cuda.cpp the following lines

I added 
#ifndef AT_CHECK
#define AT_CHECK TORCH_CHECK
#endif
