### ISSUE TITLE
RuntimeError when traning

### ISSUE THREAD

**Issue by mumipyonpyon** [BoPang1996/TubeTK#6]
Hi,
I can run the demo successfully, but I got this error when I tried to train TubeTK on MOT17.

```
TubeTK$ python launch.py --nproc_per 1 --training_script main.py --batch_size 1 --config ./configs/TubeTK_resnet_50_FPN_8frame_1stride.yaml --apex
Rank: 0 Start!
Building TubeTK Model
MOT17 data
==> Training data : 632040
==> Validation data : 5870
Selected optimization level O1:  Insert automatic casts around Pytorch functions and Tensor methods.

Defaults for this optimization level are:
enabled                : True
opt_level              : O1
cast_model_type        : None
patch_torch_functions  : True
keep_batchnorm_fp32    : None
master_weights         : None
loss_scale             : dynamic
Processing user overrides (additional kwargs that are not None)...
After processing overrides, optimization options are:
enabled                : True
opt_level              : O1
cast_model_type        : None
patch_torch_functions  : True
keep_batchnorm_fp32    : None
master_weights         : None
loss_scale             : dynamic
Training
  0%| | 0/632040 [00Gradient overflow.  Skipping step, loss scaler 0 reducing loss scale to 32768.0
Loss_cls: 4.1068,	Lo
Traceback (most recent call last):
  File "main.py", line 270, in <module>
    main(train_arg, model_arg)
  File "main.py", line 230, in main
    train(model, optimizer, data_loader, sched, tensorboard_writer, max_acc=max_acc, step_start=step)
  File "main.py", line 113, in train
    losses = run_one_iter(model, optimizer, data, scheduler, False)
  File "main.py", line 88, in run_one_iter
    scaled_loss.backward()
  File "/home/roylu/anaconda3/envs/TubeTK_rily/lib/python3.6/site-packages/torch/tensor.py", line 195, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/roylu/anaconda3/envs/TubeTK_rily/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: grad.type() == bucket_view.type() INTERNAL ASSERT FAILED at /opt/conda/conda-bld/pytorch_1579027003190/work/torch/csrc/distributed/c10d/reducer.cpp:200, please report a bug to PyTorch. Expected torch.cuda.FloatTensor, got torch.cuda.HalfTensor
Traceback (most recent call last):
  File "launch.py", line 95, in <module>
    main()
  File "launch.py", line 91, in main
    cmd=process.args)
subprocess.CalledProcessError: Command '['/home/roylu/anaconda3/envs/TubeTK_rily/bin/python', '-u', 'main.py', '--local_rank=0', '--batch_size', '1', '--config', './configs/TubeTK_resnet_50_FPN_8frame_1stride.yaml', '--apex']' returned non-zero exit status 1.
```

The error seems related to apex? But I don't have a GPU>16GB that I can run it without apex.
And what versions of python, torchvision, cuda did you use?
Thank you!

**Comment by BoPang1996** [comment]
Env: Python3.6, Pytorch1.1.0, torchvision 0.4.1, cudatoolkit 9.2

For Apex, we find it is a problem of apex's version. You can try to change line 178-181 of main.py from:

```
model = model.cuda(local_rank)
optimizer = makeOpt(train_arg, model)
 
model = torch.nn.SyncBatchNorm.convert_sync_batchnorm(model)
```

to

```
model = torch.nn.SyncBatchNorm.convert_sync_batchnorm(model)
model = model.cuda(local_rank)
optimizer = makeOpt(train_arg, model)
```

**Comment by mumipyonpyon** [comment]
After modifying the lines, the error disappears now.
Thank you very much!
