### ISSUE TITLE
demo

### ISSUE THREAD

**Issue by monsters-s** [BoPang1996/TubeTK#8]
When I use demo,although it works at first,but when at the end of the video,there is a issue.

04:20:59.660330 Frame: 150.0    Tubes: 90       Cur tracks:76   Arch tracks:164
04:20:59.777748 Frame: 151.0    Tubes: 131      Cur tracks:90   Arch tracks:164
04:20:59.927364 Frame: 152.0    Tubes: 147      Cur tracks:97   Arch tracks:164
04:21:00.061989 Frame: 153.0    Tubes: 128      Cur tracks:103  Arch tracks:164
04:21:00.183487 Frame: 154.0    Tubes: 112      Cur tracks:105  Arch tracks:164
04:21:00.294012 Frame: 155.0    Tubes: 68       Cur tracks:107  Arch tracks:164
04:21:00.373073 Frame: 156.0    Tubes: 68       Cur tracks:107  Arch tracks:164
  0%| | 0/1 [00:32<?
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/lsw/anaconda3/envs/TubeTK/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "demo.py", line 239, in match_video
    matching(tubes, save_path=os.path.join(output_dir, video_name + '.txt'), verbose=True, arg=model_arg)
  File "/home/lsw/TubeTK/post_processing/tube_iou_matching.py", line 434, in matching
    final_processing(tracks, save_path, mid_only)
  File "/home/lsw/TubeTK/post_processing/tube_iou_matching.py", line 336, in final_processing
    filt_bbox(save_path)
  File "/home/lsw/TubeTK/post_processing/tube_iou_matching.py", line 298, in filt_bbox
    res, _ = track_complete(tracks.get_group(tid).values, params[file_num][2])
KeyError: None
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "demo.py", line 370, in <module>
    main(test_arg, model_arg)
  File "demo.py", line 347, in main
    evaluate(model, loader, test_arg, model_arg, output_dir=test_arg.output_dir)
  File "demo.py", line 279, in evaluate
    p.get()
  File "/home/lsw/anaconda3/envs/TubeTK/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
KeyError: None
Traceback (most recent call last):
  File "launch.py", line 95, in <module>
    main()
  File "launch.py", line 91, in main
    cmd=process.args)
subprocess.CalledProcessError: Command '['/home/lsw/anaconda3/envs/TubeTK/bin/python', '-u', 'demo.py', '--local_rank=0', '--batch_size=3', '--config', 'configs/TubeTK_resnet_50_FPN_8frame_1stride.yaml', '--video_url', './video', '--output_dir', './vis_video']' returned non-zero exit status 1.

**Comment by chenrxi** [comment]
same as you. Do you have any methods to solve it?Thank you

**Comment by Mohammed-Abouzid** [comment]
the same problem here. any idea/solution?

**Comment by Mohammed-Abouzid** [comment]
@BoPang1996 @liyz15 
could you please have a look at this issue and kindly give us response
Thanks

**Comment by Mohammed-Abouzid** [comment]
@monsters-s @chenrxi 
in the file Post_processing/tube_iou_matching.py
I shifted lines 294-304 Into the if condition
and it worked well
